// 'use client'
import LoginForm from "@/components/auth/LoginForm";

export const metadata = {
    title: 'Signin to Your Account',
    description: 'Generated by Next.js',
}

const Login = () => {
    return (
        <div className="container">
            <div className="card">
                <LoginForm />
            </div>
        </div>
    )
}

export default Login;